#!/usr/bin/perl

use JSON::XS;

my $json = '/home/digvijay/process_order.json';
my %id = -f $json ? %{decode_json(`cat $json`)} : ();
my %new;

foreach (@ARGV) {
    next unless -f $_;
    open my $fh, '<', $_ or die "couldn't read file $_: $!";
    while (<$fh>) {
        if (/processOrder: (\w+): (\w+)$/) {
            if (not exists $id{$1}) {
                $new{$1} //= [];
                push @{$new{$1}}, $2;
            }
        }
    }
}

while (my ($id, $vals) = each %new) {
    if (grep { /^end$/ } @$vals) {
        # we saw an entire block of processOrder: tracing
        $id{$id} = $new{$id};
        if (@{$new{$id}} != 8) {
            warn sprintf "processOrder id %s only had %d of 8 entries", $id, scalar(@$vals);
        }
    }
}

open my $fh, '>', $json or die $!;
print $fh encode_json(\%id);
