#!/bin/bash -x

# this will find all *.log files in ~/tmp and compress them to <file>.gz

# NOTE: the original file gets moved (ie, gone), but since php logging can
# create logfiles on the fly, this is ok

cd ~/tmp

find . -type f -name '*.log' | 
  while read -r file; do
    now=$(date -u +%Y%m%d-%H%M)
    mv $file $file.tmp
    gzip -c $file.tmp > $file-$now.gz
    [ $? -eq 0 ] && rm $file.tmp
  done
